#define _GLOBAL_DIMMING_PANEL_PWM_MAX           0x800
#define _GLOBAL_DIMMING_PANEL_PWM_MIN           0x0FF
#define _GLOBAL_DIMMING_PANEL_PWM_DELTA_MAX     (_GLOBAL_DIMMING_PANEL_PWM_MAX - _GLOBAL_DIMMING_PANEL_PWM_MIN)
#define _GLOBAL_DIMMING_PANEL_LV_MAX            0x140
#define _GLOBAL_DIMMING_PANEL_LV_MIN            0x046
