//--------------------------------------------------
// Enumerations of User Timer Events
//--------------------------------------------------
#ifndef __TIMER_EVENT_ID_RTD2020_USER__

#define __TIMER_EVENT_ID_RTD2020_USER__

#ifndef __TIMER_EVENT_ID_RTD2020_USER__
typedef enum
{
#endif

    _USER_TIMER_EVENT_KEY_REPEAT_ENABLE,
    _USER_TIMER_EVENT_KEY_SCAN_READY,
    _USER_TIMER_EVENT_OSD_DISABLE_OSD_LOGO,
    _USER_TIMER_EVENT_OSD_SHOW_NO_CABLE,
    _USER_TIMER_EVENT_OSD_SHOW_NO_SIGNAL,
    _USER_TIMER_EVENT_OSD_SHOW_POWER_SAVING,
    _USER_TIMER_EVENT_GO_TO_POWER_SAVING,
    _USER_TIMER_EVENT_OSD_DISABLE,
    _USER_TIMER_EVENT_DO_AUTO_COLOR,
    _USER_TIMER_EVENT_DO_AUTO_ADJUST,
    _USER_TIMER_EVENT_PANEL_USED_TIMER,

#if(_COLOR_DEMO_FUNCTION == _ON)
    _USER_TIMER_EVENT_HLWIN_TYPE5_MOVE,
#endif
    _USER_TIMER_EVENT_OSD_KEYINFO_UNHIGHLIGHT,
#if(_FREESYNC_SUPPORT == _ON)
    _USER_TIMER_EVENT_OSD_SHOW_FREESYNC_VFREQ,
#endif
#if(_FREEZE_SUPPORT == _ON)
    _USER_TIMER_EVENT_OSD_DISABLE_FREEZE_MSG,
#endif

#if(_LOCAL_DIMMING_HDR10_BOOST_SUPPORT == _ON)
     _USER_TIMER_EVENT_HDR_BOOST,
     _USER_TIMER_EVENT_HDR_COOL,
#endif

#if(_DM_FUNCTION == _ON)
    _USER_TIMER_EVENT_OSD_DVISION_SHOW_LOGO_MAIN,
    _USER_TIMER_EVENT_OSD_DVISION_SHOW_LOGO_SUB,
    _USER_TIMER_EVENT_OSD_DVISION_CANCEL_LOGO_MAIN,
    _USER_TIMER_EVENT_OSD_DVISION_CANCEL_LOGO_SUB,
#endif

#if(_AUDIO_SUPPORT == _ON)
#if(_AUDIO_TTS_SUPPORT_TYPE == _AUDIO_TTS_EMBEDDED_TYPE)
    _USER_TIMER_EVENT_AUDIO_TTS_SHOW_LOGO,
    _USER_TIMER_EVENT_AUDIO_TTS_POWER_OFF,
#endif // End of #if(_AUDIO_TTS_SUPPORT_TYPE == _AUDIO_TTS_EMBEDDED_TYPE)
#endif // End of #if(_AUDIO_SUPPORT == _ON)

#if(_USB2_HOST_EHCI_MASS_STORGE_PROGRAM_SUPPORT == _ON)
    _USER_TIMER_EVENT_UPDATE_PROCESSING,
    _USER_TIMER_EVENT_WAIT_RESPONSE,
    _USER_TIMER_EVENT_UPDATE_OSD_DISABLE,
#endif
#if (_DYNAMIC_LOWBLUE_FUNCTION == _ON)
    _USER_TIMER_EVENT_EYE_PROTECT_TIMEOUT,
#endif
#ifndef __TIMER_EVENT_ID_RTD2020_USER__
} EnumTimerEventIdUser;
#endif

#endif
