/********************************************************************************/
/*   Copyright (c) 2021 Realtek Semiconductor Corp. All rights reserved.        */
/*                                                                              */
/*   SPDX-License-Identifier: LicenseRef-Realtek-Proprietary                    */
/*                                                                              */
/*   This software component is confidential and proprietary to Realtek         */
/*   Semiconductor Corp. Disclosure, reproduction, redistribution, in whole     */
/*   or in part, of this work and its derivatives without express permission    */
/*   is prohibited.                                                             */
/********************************************************************************/

//----------------------------------------------------------------------------------------------------
// ID Code      : LDPwm2SpiConfig.h
// Update Note  :
//----------------------------------------------------------------------------------------------------

//****************************************************************************
// DEFINITIONS / MACROS
//****************************************************************************
// Generated by sw tool
#define _LOCAL_DIMMING_PWM2SPI_INTERFACE_BITMAP        0x00000000      // bit map of spi interface select(EX:[0]=1 means device0 output from spi interface1)
#define _LOCAL_DIMMING_PWM2SPI_SPI0_DEV_NUM            2               // Device Number on SPI0 Interface
#define _LOCAL_DIMMING_PWM2SPI_SPI1_DEV_NUM            0               // Device Number on SPI1 Interface

#define _LOCAL_DIMMING_PWM2SPI_MAX_DATA_BYTE_NUM       32              // Max Data Byte Number (32 for 16 zone LED Driver)
#define _LOCAL_DIMMING_PWM2SPI_MAX_DUMMY_BYTE_NUM      1              // Max Dummy Byte Number of this setting


//****************************************************************************
// STRUCT / TYPE / ENUM DEFINITTIONS
//****************************************************************************


//****************************************************************************
// CODE TABLES
//****************************************************************************
