#define _PANEL_PWM_MAX                          0x800
#define _PANEL_PWM_MIN                          0x0FF
#define _PANEL_PWM_DELTA_MAX                    (_PANEL_PWM_MAX - _PANEL_PWM_MIN)
#define _PANEL_LV_MAX                           0x174
#define _PANEL_LV_MIN                           0x05D
#define _REGION0_PWM_TO_LV_OWN                  0x0B
#define _REGION0_PWM_TO_LV_REGION1              0x22
#define _REGION1_PWM_TO_LV_OWN                  0x0B
#define _REGION1_PWM_TO_LV_REGION0              0x22
#define _REGION1_PWM_TO_LV_REGION2              0x21
#define _REGION2_PWM_TO_LV_OWN                  0x0B
#define _REGION2_PWM_TO_LV_REGION1              0x22
#define _REGION2_PWM_TO_LV_REGION3              0x20
#define _REGION3_PWM_TO_LV_OWN                  0x0A
#define _REGION3_PWM_TO_LV_REGION2              0x1F
#define _REGION3_PWM_TO_LV_REGION4              0x1D
#define _REGION4_PWM_TO_LV_OWN                  0x0A
#define _REGION4_PWM_TO_LV_REGION3              0x1E
#define _REGION4_PWM_TO_LV_REGION5              0x1E
#define _REGION5_PWM_TO_LV_OWN                  0x0A
#define _REGION5_PWM_TO_LV_REGION4              0x1E
#define _REGION5_PWM_TO_LV_REGION6              0x1D
#define _REGION6_PWM_TO_LV_OWN                  0x09
#define _REGION6_PWM_TO_LV_REGION5              0x1D
#define _REGION6_PWM_TO_LV_REGION7              0x1A
#define _REGION7_PWM_TO_LV_OWN                  0x08
#define _REGION7_PWM_TO_LV_REGION6              0x1C
