BYTE * code tOSD_TABLE_LANGUAGE_FONT_BODY_FACTORY[] =
{
tsFontCBody0_FACTORY,
//NULL,
};    //*tOSD_TABLE_LANGUAGE_FONT_BODY_FACTORY

code int tOSD_TABLE_LANGUAGE_FONT_COUNT_FACTORY[] =
{
sizeof(tsFontCBody0_FACTORY) / 27,
//0,
};    //tOSD_TABLE_LANGUAGE_FONT_COUNT_FACTORY

//max count = 88

