/********************************************************************************/
/*   Copyright (c) 2021 Realtek Semiconductor Corp. All rights reserved.        */
/*                                                                              */
/*   SPDX-License-Identifier: LicenseRef-Realtek-Proprietary                    */
/*                                                                              */
/*   This software component is confidential and proprietary to Realtek         */
/*   Semiconductor Corp. Disclosure, reproduction, redistribution, in whole     */
/*   or in part, of this work and its derivatives without express permission    */
/*   is prohibited.                                                             */
/********************************************************************************/

//----------------------------------------------------------------------------------------------------
// ID Code      : RTD2020OsdTextTableDefineFactory.h
// Update Note  :
//----------------------------------------------------------------------------------------------------


//--------------------------------------------------
// Definitions of OSD Font Body Extension
//--------------------------------------------------
#define _FONT_SELECT_EXT1_FACTORY               251
#define _FONT_SELECT_EXT2_FACTORY               252
#define _NEXT_LINE_FACTORY                      253
#define _FONT_BLANK_PIXEL_FACTORY               254
#define _FONT_SELECT_OFFSET1_FACTORY            251
#define _FONT_SELECT_OFFSET2_FACTORY            502
#define _GLOBAL_FONT_END_OFFSET_FACTORY         (0)


//****************************************************************************
// Definitions of User
//****************************************************************************
typedef enum
{
_OSD_TEXT_NULL_FACT,
_OSD_TEXT_AUTO_COLOR_FACT,
_OSD_TEXT_AUTO_COLOR_TYPE_FACT,
_OSD_TEXT_BURN_IN_FACT,
_OSD_TEXT_RESET_PANEL_TIME_FACT,
_OSD_TEXT_HOUR_FACT,
_OSD_TEXT_MIN_FACT,
_OSD_TEXT_PANEL_TIME_FACT,
_OSD_TEXT_CT9300_FACT,
_OSD_TEXT_CT7500_FACT,
_OSD_TEXT_CT6500_FACT,
_OSD_TEXT_CT5800_FACT,
_OSD_TEXT_USER_FACT,
_OSD_TEXT_SRGB_FACT,
_OSD_TEXT_ADCOFFSET_FACT,
_OSD_TEXT_ADC_GAIN_FACT,
_OSD_TEXT_B_G_COLOR_FACT,
_OSD_TEXT_SSC_FACT,
_OSD_TEXT_SSC_SPEED_FACT,
_OSD_TEXT_LVDS_DRIVING_FACT,
_OSD_TEXT_DP_HPD_DC_OFF_SUPPORT_FACT,
_OSD_TEXT_HDMI_HPD_SUPPOT_FACT,
_OSD_TEXT_HDMI_HDP_TIME_FACT,
_OSD_TEXT_DP_AUX_DIFF_MODE_FACT,
_OSD_TEXT_OSD_DOUBLE_SIZE_FACT,
_OSD_TEXT_COLORIMETRY_SAEMLESS_FACT,
_OSD_TEXT_DP_AUX_ADJ_SETTING_FACT,
_OSD_TEXT_DP_IRQ_TIME_FACT,
_OSD_TEXT_PAGE_FACT,
_OSD_TEXT_EXIT_FACT,
_OSD_TEXT_RED_FACT,
_OSD_TEXT_GREEN_FACT,
_OSD_TEXT_BLUE_FACT,
_OSD_TEXT_NO_FACT,
_OSD_TEXT_YES_FACT,
_OSD_TEXT_FAIL_FACT,
_OSD_TEXT_PASS_FACT,
_OSD_TEXT_INTERNEL_FACT,
_OSD_TEXT_EXTERNAL_FACT,
_OSD_TEXT_OFF_FACT,
_OSD_TEXT_ON_FACT,
_OSD_TEXT_DISABLE_FACT,
_OSD_TEXT_ENABLE_FACT,
_OSD_TEXT_SINGLE_FACT,
_OSD_TEXT_DIFFERNTIAL_FACT,
_OSD_TEXT_RBR_FACT,
_OSD_TEXT_HBR_FACT,
_OSD_TEXT_HBR2_FACT,
_OSD_TEXT_HBR3_FACT,
_OSD_TEXT_ONE_LANE_FACT,
_OSD_TEXT_TWO_LANE_FACT,
_OSD_TEXT_FOUR_LANE_FACT,
_OSD_TEXT_SWING_LV0_FACT,
_OSD_TEXT_SWING_LV1_FACT,
_OSD_TEXT_SWING_LV2_FACT,
_OSD_TEXT_SWING_LV3_FACT,
_OSD_TEXT_DP_DEBUG_MSG_FACT,
_OSD_TEXT_P_E_LV0_FACT,
_OSD_TEXT_P_E_LV1_FACT,
_OSD_TEXT_P_E_LV2_FACT,
_OSD_TEXT_P_E_LV3_FACT,
_OSD_TEXT_LANE0_FACT,
_OSD_TEXT_LANE1_FACT,
_OSD_TEXT_LANE2_FACT,
_OSD_TEXT_LANE3_FACT,
_OSD_TEXT_SPEED33_K_FACT,
_OSD_TEXT_SPEED66_K_FACT,
_OSD_TEXT_SPEED30_K_FACT,
_OSD_TEXT_C20MA_FACT,
_OSD_TEXT_C25MA_FACT,
_OSD_TEXT_C30MA_FACT,
_OSD_TEXT_C35MA_FACT,
_OSD_TEXT_C15MA_FACT,

_OSD_TEXT_RGB_FACT,
_OSD_TEXT_YCBCR444_FACT,
_OSD_TEXT_YCBCR422_FACT,
_OSD_TEXT_YCBCR420_FACT,
_OSD_TEXT_FULL_FACT,
_OSD_TEXT_LIMIT_FACT,
_OSD_TEXT_DEFAULT_FACT,
_OSD_TEXT_MODEL_NAME_FACT,
_OSD_TEXT_FRAME_SYNC_MEMORY_FACT,
_OSD_TEXT_FRAME_SYNC_LINE_BUFFER_FACT,
_OSD_TEXT_FREE_RUN_MEMORY_FACT,
_OSD_TEXT_MN_FRAME_SYNC_MEMORY_FACT,
_OSD_TEXT_FREE_RUN_NO_INPUT_FACT,
_OSD_TEXT_H_V_SCALER_DOWN_FACT,
_OSD_TEXT_OD_FACT,

} EnumOSDStringText_FACTORYDef;    //StringText_FACTORY


typedef enum
{
_FONT_SPACE_1_FACTORY,
U0020_FACTORY,
U0025_FACTORY,
U0027_FACTORY,
U0028_FACTORY,
U0029_FACTORY,
U002C_FACTORY,
U002D_FACTORY,
U002E_FACTORY,
U002F_FACTORY,
U0030_FACTORY,
U0031_FACTORY,
U0032_FACTORY,
U0033_FACTORY,
U0034_FACTORY,
U0035_FACTORY,
U0036_FACTORY,
U0037_FACTORY,
U0038_FACTORY,
U0039_FACTORY,
U003A_FACTORY,
U003B_FACTORY,
U003F_FACTORY,
U0040_FACTORY_0,U0040_FACTORY_1,
U0041_FACTORY,
U0042_FACTORY,
U0043_FACTORY,
U0044_FACTORY,
U0045_FACTORY,
U0046_FACTORY,
U0047_FACTORY,
U0048_FACTORY,
U0049_FACTORY,
U004A_FACTORY,
U004B_FACTORY,
U004C_FACTORY,
U004D_FACTORY_0,U004D_FACTORY_1,
U004E_FACTORY,
U004F_FACTORY,
U0050_FACTORY,
U0051_FACTORY_0,U0051_FACTORY_1,
U0052_FACTORY,
U0053_FACTORY,
U0054_FACTORY,
U0055_FACTORY,
U0056_FACTORY,
U0057_FACTORY_0,U0057_FACTORY_1,
U0058_FACTORY,
U0059_FACTORY,
U005A_FACTORY,
U0061_FACTORY,
U0062_FACTORY,
U0063_FACTORY,
U0064_FACTORY,
U0065_FACTORY,
U0066_FACTORY,
U0067_FACTORY,
U0068_FACTORY,
U0069_FACTORY,
U006A_FACTORY,
U006B_FACTORY,
U006C_FACTORY,
U006D_FACTORY,
U006E_FACTORY,
U006F_FACTORY,
U0070_FACTORY,
U0071_FACTORY,
U0072_FACTORY,
U0073_FACTORY,
U0074_FACTORY,
U0075_FACTORY,
U0076_FACTORY,
U0077_FACTORY,
U0078_FACTORY,
U0079_FACTORY,
U007A_FACTORY,
U2019_FACTORY,
U201C_FACTORY,
U201D_FACTORY,
U2026_FACTORY,
U3002_FACTORY,
UFF08_FACTORY,
UFF09_FACTORY,
UFF0C_FACTORY,
_GLOBAL_FONT_END_FACTORY,
} EnumOSDFontCBody0_FACTORYDef;    //FontCBody0_FACTORY, 88

