//--------------------------------------------------
// Enumerations of System Timer Events
//--------------------------------------------------
#ifndef __TIMER_EVENT_ID_SYSTEM__

#define __TIMER_EVENT_ID_SYSTEM__

#ifndef __TIMER_EVENT_ID_SYSTEM__
typedef enum
{
#endif

    _SYSTEM_TIMER_EVENT_SOURCE_CLEAR_DETECTING,
    _SYSTEM_TIMER_EVENT_JUDGE_ACTIVE_STATE,
    _SYSTEM_TIMER_EVENT_JUDGE_NOSUPPORT_STATE,
    _SYSTEM_TIMER_EVENT_SOURCE_NOSUPPORT_STATE,
    _SYSTEM_TIMER_EVENT_SOURCE_NOSIGNAL_STATE,
    _SYSTEM_TIMER_EVENT_POWER_FAKE_OFF_TO_OFF,

#if(_DP_HDCP_POWER_OFF_HANDSHAKE_SUPPORT == _ON)
    _SYSTEM_TIMER_EVENT_POWER_FAKE_SAVING_TO_SAVING,
#endif

    _SYSTEM_TIMER_EVENT_PANEL_BACKLIGHT_ON,
    _SYSTEM_TIMER_EVENT_PANEL_POWER_OFF,

#if(_HDMI_EXTERNAL_SWITCH_SUPPORT == _ON)
    _SYSTEM_TIMER_EVENT_SOURCE_HDMI_SWITCH_TIMEOUT,
#endif

#if(_SOURCE_AUTO_SEARCH_STYLE == _SOURCE_POLLING_ASUS_STYLE)
    _SYSTEM_TIMER_EVENT_SOURCE_ASUS_START_AUTO,
#endif

#if(_SOURCE_AUTO_SEARCH_STYLE == _SOURCE_POLLING_EIZO_STYLE)
    _SYSTEM_TIMER_EVENT_SOURCE_EIZO_SEARCH_FINISH,
#endif

#if(_DUAL_DP_SUPPORT == _ON)
    _SYSTEM_TIMER_EVENT_SOURCE_DP_DUAL_SWITCH_TIMEOUT,
#endif

#if(_EMBEDDED_DAC_SUPPORT == _ON)
    _SYSTEM_TIMER_EVENT_AUDIO_DAC_WAIT_VCM_INITIAL,
    _SYSTEM_TIMER_EVENT_AUDIO_DAC_WAIT_VCM_CHARGE,
    _SYSTEM_TIMER_EVENT_AUDIO_DAC_WAIT_DEPOP_TO_NORMAL,
#endif

#if((_USB2_HOST_SUPPORT == _ON) && (_USB2_HOST_FW_SUPPORT_TYPE == _FW_MAIN_LOOP))
    _SYSTEM_TIMER_EVENT_USB_U2HOST_DETECT,
#endif

#if(_TYPE_C_PORT_CTRL_SUPPORT == _ON)
    _SYSTEM_TIMER_EVENT_LOCAL_POWER_DETECT,
#endif

#if(_D0_TYPE_C_PORT_CTRL_SUPPORT == _ON)
    _SYSTEM_TIMER_EVENT_D0_TYPE_C_CONNECTION_DET,

#if((_TYPE_C_MODAL_OPERATION_SUPPORT == _ON) && (_TYPE_C_VENDOR_ALT_MODE == _TYPE_C_LENOVO_ALT_MODE))
    _SYSTEM_TIMER_EVENT_D0_TYPE_C_LENOVO_RCV_DEVICE_TYPE_TIMEOUT,
#endif

#if(_D0_TYPE_C_PORT_CTRL_TYPE == _PORT_CTRL_RTS)
    _SYSTEM_TIMER_EVENT_D0_TYPE_C_STATUS_DETECT,
#if((_TYPE_C_MODAL_OPERATION_SUPPORT == _ON) && (_TYPE_C_VENDOR_ALT_MODE == _TYPE_C_LENOVO_ALT_MODE))
    _SYSTEM_TIMER_EVENT_D0_TYPE_C_LENOVO_ALT_MODE_DETECT,
    _SYSTEM_TIMER_EVENT_D0_TYPE_C_LENOVO_DEVICE_TYPE_DETECT,
#endif
#endif  // End of #if(_D0_TYPE_C_PORT_CTRL_TYPE == _PORT_CTRL_RTS)

#if(_D0_TYPE_C_PORT_CTRL_TYPE == _PORT_CTRL_RTD)
    _SYSTEM_TIMER_EVENT_D0_TYPE_C_RTD_STATUS_DETECT,
#endif  // End of #if(_D0_TYPE_C_PORT_CTRL_TYPE == _PORT_CTRL_RTD)

#if(_D0_USB_HUB_COMMUNICATION_SUPPORT == _ON)
    _SYSTEM_TIMER_EVENT_D0_USBHUB_DETECT,
#endif

#if((_D0_TYPE_C_BILLBOARD_TYPE == _BILLBOARD_SCALER) || (_D0_TYPE_C_BILLBOARD_TYPE == _BILLBOARD_HUB))
    _SYSTEM_TIMER_EVENT_D0_ENABLE_BILLBOARD,
#endif
#endif  // End of #if(_D0_TYPE_C_PORT_CTRL_SUPPORT == _ON)

#if(_D1_TYPE_C_PORT_CTRL_SUPPORT == _ON)
    _SYSTEM_TIMER_EVENT_D1_TYPE_C_CONNECTION_DET,

#if((_TYPE_C_MODAL_OPERATION_SUPPORT == _ON) && (_TYPE_C_VENDOR_ALT_MODE == _TYPE_C_LENOVO_ALT_MODE))
    _SYSTEM_TIMER_EVENT_D1_TYPE_C_LENOVO_RCV_DEVICE_TYPE_TIMEOUT,
#endif

#if(_D1_TYPE_C_PORT_CTRL_TYPE == _PORT_CTRL_RTS)
    _SYSTEM_TIMER_EVENT_D1_TYPE_C_STATUS_DETECT,
#if((_TYPE_C_MODAL_OPERATION_SUPPORT == _ON) && (_TYPE_C_VENDOR_ALT_MODE == _TYPE_C_LENOVO_ALT_MODE))
    _SYSTEM_TIMER_EVENT_D1_TYPE_C_LENOVO_ALT_MODE_DETECT,
    _SYSTEM_TIMER_EVENT_D1_TYPE_C_LENOVO_DEVICE_TYPE_DETECT,
#endif
#endif  // End of #if(_D1_TYPE_C_PORT_CTRL_TYPE == _PORT_CTRL_RTS)

#if(_D1_TYPE_C_PORT_CTRL_TYPE == _PORT_CTRL_RTD)
    _SYSTEM_TIMER_EVENT_D1_TYPE_C_RTD_STATUS_DETECT,
#endif  // End of #if(_D1_TYPE_C_PORT_CTRL_TYPE == _PORT_CTRL_RTD)

#if(_D1_USB_HUB_COMMUNICATION_SUPPORT == _ON)
    _SYSTEM_TIMER_EVENT_D1_USBHUB_DETECT,
#endif

#if((_D1_TYPE_C_BILLBOARD_TYPE == _BILLBOARD_SCALER) || (_D1_TYPE_C_BILLBOARD_TYPE == _BILLBOARD_HUB))
    _SYSTEM_TIMER_EVENT_D1_ENABLE_BILLBOARD,
#endif
#endif  // End of #if(_D1_TYPE_C_PORT_CTRL_SUPPORT == _ON)

#if(_D2_TYPE_C_PORT_CTRL_SUPPORT == _ON)
    _SYSTEM_TIMER_EVENT_D2_TYPE_C_CONNECTION_DET,

#if((_TYPE_C_MODAL_OPERATION_SUPPORT == _ON) && (_TYPE_C_VENDOR_ALT_MODE == _TYPE_C_LENOVO_ALT_MODE))
    _SYSTEM_TIMER_EVENT_D2_TYPE_C_LENOVO_RCV_DEVICE_TYPE_TIMEOUT,
#endif

#if(_D2_TYPE_C_PORT_CTRL_TYPE == _PORT_CTRL_RTS)
    _SYSTEM_TIMER_EVENT_D2_TYPE_C_STATUS_DETECT,
#if((_TYPE_C_MODAL_OPERATION_SUPPORT == _ON) && (_TYPE_C_VENDOR_ALT_MODE == _TYPE_C_LENOVO_ALT_MODE))
    _SYSTEM_TIMER_EVENT_D2_TYPE_C_LENOVO_ALT_MODE_DETECT,
    _SYSTEM_TIMER_EVENT_D2_TYPE_C_LENOVO_DEVICE_TYPE_DETECT,
#endif
#endif  // End of #if(_D2_TYPE_C_PORT_CTRL_TYPE == _PORT_CTRL_RTS)

#if(_D2_TYPE_C_PORT_CTRL_TYPE == _PORT_CTRL_RTD)
    _SYSTEM_TIMER_EVENT_D2_TYPE_C_RTD_STATUS_DETECT,
#endif  // End of #if(_D2_TYPE_C_PORT_CTRL_TYPE == _PORT_CTRL_RTD)

#if(_D2_USB_HUB_COMMUNICATION_SUPPORT == _ON)
    _SYSTEM_TIMER_EVENT_D2_USBHUB_DETECT,
#endif

#if((_D2_TYPE_C_BILLBOARD_TYPE == _BILLBOARD_SCALER) || (_D2_TYPE_C_BILLBOARD_TYPE == _BILLBOARD_HUB))
    _SYSTEM_TIMER_EVENT_D2_ENABLE_BILLBOARD,
#endif
#endif  // End of #if(_D2_TYPE_C_PORT_CTRL_SUPPORT == _ON)

#if(_P0_TYPE_C_PORT_CTRL_SUPPORT == _ON)
    _SYSTEM_TIMER_EVENT_P0_TYPE_C_CONNECTION_DET,

#if((_TYPE_C_MODAL_OPERATION_SUPPORT == _ON) && (_TYPE_C_VENDOR_ALT_MODE == _TYPE_C_LENOVO_ALT_MODE))
    _SYSTEM_TIMER_EVENT_P0_TYPE_C_LENOVO_RCV_DEVICE_TYPE_TIMEOUT,
#endif

#if(_P0_TYPE_C_PORT_CTRL_TYPE == _PORT_CTRL_RTS)
    _SYSTEM_TIMER_EVENT_P0_TYPE_C_STATUS_DETECT,
#if((_TYPE_C_MODAL_OPERATION_SUPPORT == _ON) && (_TYPE_C_VENDOR_ALT_MODE == _TYPE_C_LENOVO_ALT_MODE))
    _SYSTEM_TIMER_EVENT_P0_TYPE_C_LENOVO_ALT_MODE_DETECT,
    _SYSTEM_TIMER_EVENT_P0_TYPE_C_LENOVO_DEVICE_TYPE_DETECT,
#endif
#endif  // End of #if(_P0_TYPE_C_PORT_CTRL_TYPE == _PORT_CTRL_RTS)

#if(_P0_TYPE_C_PORT_CTRL_TYPE == _PORT_CTRL_RTD)
    _SYSTEM_TIMER_EVENT_P0_TYPE_C_RTD_STATUS_DETECT,
#endif  // End of #if(_P0_TYPE_C_PORT_CTRL_TYPE == _PORT_CTRL_RTD)

#if((_P0_TYPE_C_BILLBOARD_TYPE == _BILLBOARD_SCALER) || (_P0_TYPE_C_BILLBOARD_TYPE == _BILLBOARD_HUB))
    _SYSTEM_TIMER_EVENT_P0_ENABLE_BILLBOARD,
#endif
#endif  // End of #if(_P0_TYPE_C_PORT_CTRL_SUPPORT == _ON)

#if(_P1_TYPE_C_PORT_CTRL_SUPPORT == _ON)
    _SYSTEM_TIMER_EVENT_P1_TYPE_C_CONNECTION_DET,

#if((_TYPE_C_MODAL_OPERATION_SUPPORT == _ON) && (_TYPE_C_VENDOR_ALT_MODE == _TYPE_C_LENOVO_ALT_MODE))
    _SYSTEM_TIMER_EVENT_P1_TYPE_C_LENOVO_RCV_DEVICE_TYPE_TIMEOUT,
#endif

#if(_P1_TYPE_C_PORT_CTRL_TYPE == _PORT_CTRL_RTS)
    _SYSTEM_TIMER_EVENT_P1_TYPE_C_STATUS_DETECT,
#if((_TYPE_C_MODAL_OPERATION_SUPPORT == _ON) && (_TYPE_C_VENDOR_ALT_MODE == _TYPE_C_LENOVO_ALT_MODE))
    _SYSTEM_TIMER_EVENT_P1_TYPE_C_LENOVO_ALT_MODE_DETECT,
    _SYSTEM_TIMER_EVENT_P1_TYPE_C_LENOVO_DEVICE_TYPE_DETECT,
#endif
#endif  // End of #if(_P1_TYPE_C_PORT_CTRL_TYPE == _PORT_CTRL_RTS)

#if(_P1_TYPE_C_PORT_CTRL_TYPE == _PORT_CTRL_RTD)
    _SYSTEM_TIMER_EVENT_P1_TYPE_C_RTD_STATUS_DETECT,
#endif  // End of #if(_P1_TYPE_C_PORT_CTRL_TYPE == _PORT_CTRL_RTD)

#if((_P1_TYPE_C_BILLBOARD_TYPE == _BILLBOARD_SCALER) || (_P1_TYPE_C_BILLBOARD_TYPE == _BILLBOARD_HUB))
    _SYSTEM_TIMER_EVENT_P1_ENABLE_BILLBOARD,
#endif
#endif  // End of #if(_P1_TYPE_C_PORT_CTRL_SUPPORT == _ON)

#if(_P2_TYPE_C_PORT_CTRL_SUPPORT == _ON)
    _SYSTEM_TIMER_EVENT_P2_TYPE_C_CONNECTION_DET,

#if((_TYPE_C_MODAL_OPERATION_SUPPORT == _ON) && (_TYPE_C_VENDOR_ALT_MODE == _TYPE_C_LENOVO_ALT_MODE))
    _SYSTEM_TIMER_EVENT_P2_TYPE_C_LENOVO_RCV_DEVICE_TYPE_TIMEOUT,
#endif

#if(_P2_TYPE_C_PORT_CTRL_TYPE == _PORT_CTRL_RTS)
    _SYSTEM_TIMER_EVENT_P2_TYPE_C_STATUS_DETECT,
#if((_TYPE_C_MODAL_OPERATION_SUPPORT == _ON) && (_TYPE_C_VENDOR_ALT_MODE == _TYPE_C_LENOVO_ALT_MODE))
    _SYSTEM_TIMER_EVENT_P2_TYPE_C_LENOVO_ALT_MODE_DETECT,
    _SYSTEM_TIMER_EVENT_P2_TYPE_C_LENOVO_DEVICE_TYPE_DETECT,
#endif
#endif  // End of #if(_P2_TYPE_C_PORT_CTRL_TYPE == _PORT_CTRL_RTS)

#if(_P2_TYPE_C_PORT_CTRL_TYPE == _PORT_CTRL_RTD)
    _SYSTEM_TIMER_EVENT_P2_TYPE_C_RTD_STATUS_DETECT,
#endif  // End of #if(_P2_TYPE_C_PORT_CTRL_TYPE == _PORT_CTRL_RTD)

#if((_P2_TYPE_C_BILLBOARD_TYPE == _BILLBOARD_SCALER) || (_P2_TYPE_C_BILLBOARD_TYPE == _BILLBOARD_HUB))
    _SYSTEM_TIMER_EVENT_P2_ENABLE_BILLBOARD,
#endif
#endif  // End of #if(_P2_TYPE_C_PORT_CTRL_SUPPORT == _ON)

#if(_P3_TYPE_C_PORT_CTRL_SUPPORT == _ON)
    _SYSTEM_TIMER_EVENT_P3_TYPE_C_CONNECTION_DET,

#if((_TYPE_C_MODAL_OPERATION_SUPPORT == _ON) && (_TYPE_C_VENDOR_ALT_MODE == _TYPE_C_LENOVO_ALT_MODE))
    _SYSTEM_TIMER_EVENT_P3_TYPE_C_LENOVO_RCV_DEVICE_TYPE_TIMEOUT,
#endif

#if(_P3_TYPE_C_PORT_CTRL_TYPE == _PORT_CTRL_RTS)
    _SYSTEM_TIMER_EVENT_P3_TYPE_C_STATUS_DETECT,
#if((_TYPE_C_MODAL_OPERATION_SUPPORT == _ON) && (_TYPE_C_VENDOR_ALT_MODE == _TYPE_C_LENOVO_ALT_MODE))
    _SYSTEM_TIMER_EVENT_P3_TYPE_C_LENOVO_ALT_MODE_DETECT,
    _SYSTEM_TIMER_EVENT_P3_TYPE_C_LENOVO_DEVICE_TYPE_DETECT,
#endif
#endif  // End of #if(_P3_TYPE_C_PORT_CTRL_TYPE == _PORT_CTRL_RTS)

#if(_P3_TYPE_C_PORT_CTRL_TYPE == _PORT_CTRL_RTD)
    _SYSTEM_TIMER_EVENT_P3_TYPE_C_RTD_STATUS_DETECT,
#endif  // End of #if(_P3_TYPE_C_PORT_CTRL_TYPE == _PORT_CTRL_RTD)

#if((_P3_TYPE_C_BILLBOARD_TYPE == _BILLBOARD_SCALER) || (_P3_TYPE_C_BILLBOARD_TYPE == _BILLBOARD_HUB))
    _SYSTEM_TIMER_EVENT_P3_ENABLE_BILLBOARD,
#endif
#endif  // End of #if(_P3_TYPE_C_PORT_CTRL_SUPPORT == _ON)

#if(_P4_TYPE_C_PORT_CTRL_SUPPORT == _ON)
    _SYSTEM_TIMER_EVENT_P4_TYPE_C_CONNECTION_DET,

#if((_TYPE_C_MODAL_OPERATION_SUPPORT == _ON) && (_TYPE_C_VENDOR_ALT_MODE == _TYPE_C_LENOVO_ALT_MODE))
    _SYSTEM_TIMER_EVENT_P4_TYPE_C_LENOVO_RCV_DEVICE_TYPE_TIMEOUT,
#endif

#if(_P4_TYPE_C_PORT_CTRL_TYPE == _PORT_CTRL_RTS)
    _SYSTEM_TIMER_EVENT_P4_TYPE_C_STATUS_DETECT,
#if((_TYPE_C_MODAL_OPERATION_SUPPORT == _ON) && (_TYPE_C_VENDOR_ALT_MODE == _TYPE_C_LENOVO_ALT_MODE))
    _SYSTEM_TIMER_EVENT_P4_TYPE_C_LENOVO_ALT_MODE_DETECT,
    _SYSTEM_TIMER_EVENT_P4_TYPE_C_LENOVO_DEVICE_TYPE_DETECT,
#endif
#endif  // End of #if(_P4_TYPE_C_PORT_CTRL_TYPE == _PORT_CTRL_RTS)

#if(_P4TYPE_C_PORT_CTRL_TYPE == _PORT_CTRL_RTD)
    _SYSTEM_TIMER_EVENT_P4_TYPE_C_RTD_STATUS_DETECT,
#endif  // End of #if(_P4_TYPE_C_PORT_CTRL_TYPE == _PORT_CTRL_RTD)

#if((_P4_TYPE_C_BILLBOARD_TYPE == _BILLBOARD_SCALER) || (_P4_TYPE_C_BILLBOARD_TYPE == _BILLBOARD_HUB))
    _SYSTEM_TIMER_EVENT_P4_ENABLE_BILLBOARD,
#endif
#endif  // End of #if(_P4_TYPE_C_PORT_CTRL_SUPPORT == _ON)

#if(_ADAPTOR_TYPE_C_PORT_CTRL_SUPPORT == _ON)
    _SYSTEM_TIMER_EVENT_ADAPTOR_TYPE_C_CONNECTION_DET,

#if(_ADAPTOR_TYPE_C_PORT_CTRL_TYPE == _PORT_CTRL_RTS)
    _SYSTEM_TIMER_EVENT_ADAPTOR_TYPE_C_STATUS_DETECT,
#endif  // End of #if(_ADAPTOR_TYPE_C_PORT_CTRL_TYPE == _PORT_CTRL_RTS)
#endif  // End of #if(_ADAPTOR_TYPE_C_PORT_CTRL_SUPPORT == _ON)

#if(_ADAPTOR_TYPE_C_PORT_CTRL_TYPE == _PORT_CTRL_RTD)
    _SYSTEM_TIMER_EVENT_ADAPTOR_TYPE_C_RTD_STATUS_DETECT,
#endif  // End of #if(_ADAPTOR_TYPE_C_PORT_CTRL_TYPE == _PORT_CTRL_RTD)

#if(_TYPE_C_PORT_CTRL_SUPPORT == _ON)
#if(_PORT_CTRL_RTS_SUPPORT == _ON)
#if((_TYPE_C_MODAL_OPERATION_SUPPORT == _ON) && (_TYPE_C_VENDOR_ALT_MODE == _TYPE_C_LENOVO_ALT_MODE))
    _SYSTEM_TIMER_EVENT_TYPE_C_LENOVO_ALT_MODE_URGENT_EVENT_TIMEOUT,
#endif
#endif
#endif

#if(_USB_HUB_SUPPORT == _ON)
    _SYSTEM_TIMER_EVENT_USB_HUB_DISABLE_DURATION_TIMEOUT,

#if(_D0_USB_HUB_SUPPORT == _ON)
    _SYSTEM_TIMER_EVENT_D0_USB_FROCE_ENABLE,
#endif  // End of #if(_D0_USB_HUB_SUPPORT == _ON)

#if(_D1_USB_HUB_SUPPORT == _ON)
    _SYSTEM_TIMER_EVENT_D1_USB_FROCE_ENABLE,
#endif  // End of #if(_D1_USB_HUB_SUPPORT == _ON)

#if(_D2_USB_HUB_SUPPORT == _ON)
    _SYSTEM_TIMER_EVENT_D2_USB_FROCE_ENABLE,
#endif  // End of #if(_D2_USB_HUB_SUPPORT == _ON)
#endif

#if(_AUTO_TEST_SUPPORT == _ON)
    _SYSTEM_TIMER_EVENT_AUTO_TEST_OSD_KEY_MSG,
#endif

#if(_DDCCI_AUTO_SWITCH_SUPPORT == _ON)
    _SYSTEM_TIMER_EVENT_CLR_DDCCI0_RECEIVE_COMMAND_NOT_FINISH,
#endif

#if((_2P_FRAME_SYNC_SUPPORT == _ON) && (_2P_FRAME_SYNC_DEBOUNCE_TIME != 0))
    _SYSTEM_TIMER_EVENT_2P_FRAME_SYNC_DEBOUNCE,
#endif

#if(_HP_SOURCE_SCAN_SUPPORT == _ON)
    _SYSTEM_TIMER_EVENT_SOURCE_HP_CANCEL_MANUAL_SWITCH_PORT,
#endif

#if(_FW_UPDATE_FOREGROUND_SUPPORT == _ON)
    _SYSTEM_TIMER_EVENT_FW_UPDATE_FOREGROUND_EXIT,
#endif

#if(_DM_FUNCTION == _ON)
#if(_DM_DEMO_FUNCTION == _ON)
    _SYSTEM_TIMER_EVENT_DM_DEMO_FUNCTION,
#endif
#endif

#if(_HDMI_CEC_SUPPORT == _ON)
#if(_AUDIO_ARC_SUPPORT == _ON)
    _SYSTEM_TIMER_EVENT_CEC_RETRY_REQUEST_ARC_INITIATE,
    _SYSTEM_TIMER_EVENT_CEC_RETRY_REQUEST_ARC_TERMINATE,
#endif

#if(_HDMI_CEC_KERNEL_HAL_SUPPORT == _ON)
    _SYSTEM_TIMER_EVENT_CEC_RETRY_PHYSICAL_ADDRESS,
    _SYSTEM_TIMER_EVENT_CEC_WAIT_FOR_AUDIO_DESCRIPTOR_REPLY,
#endif
#endif

#ifndef __TIMER_EVENT_ID_SYSTEM__
} EnumTimerEventIdSystem;
#endif

#endif
