//--------------------------------------------------
// Enumerations of Scaler Timer Events
//--------------------------------------------------
#ifndef __TIMER_EVENT_ID_SCALER__

#define __TIMER_EVENT_ID_SCALER__

#ifndef __TIMER_EVENT_ID_SCALER__
typedef enum
{
#endif

#if(_HDMI_SUPPORT == _ON)
#if(_D1_HDMI_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_D1_TMDS_HPD_ASSERTED,
    _SCALER_TIMER_EVENT_HDMI_D1_HPD_5VPIN_CHECK,
#endif
#if(_D2_HDMI_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_D2_TMDS_HPD_ASSERTED,
    _SCALER_TIMER_EVENT_HDMI_D2_HPD_5VPIN_CHECK,
#endif
#if(_D3_HDMI_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_D3_TMDS_HPD_ASSERTED,
    _SCALER_TIMER_EVENT_HDMI_D3_HPD_5VPIN_CHECK,
#endif
#if(_D4_HDMI_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_D4_TMDS_HPD_ASSERTED,
    _SCALER_TIMER_EVENT_HDMI_D4_HPD_5VPIN_CHECK,
#endif
#if(_D5_HDMI_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_D5_TMDS_HPD_ASSERTED,
    _SCALER_TIMER_EVENT_HDMI_D5_HPD_5VPIN_CHECK,
#endif

#if(_TMDS_MAC_RX3_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_RX3_TMDS_VIDEO_DETECT,
#if(_HDMI_MAC_RX3_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_RX3_TMDS_HDMI_PACKET_DETECT,

#if(_HDMI_ADVANCED_HDR10_SUPPORT_MODE != _ADVANCED_HDR10_NONE)
    _SCALER_TIMER_EVENT_RX3_HDMI_ADVANCED_HDR10_DETECT,
#endif

#if(_DM_FUNCTION == _ON)
    _SCALER_TIMER_EVENT_RX3_HDMI_DM_DETECT,
#endif

    _SCALER_TIMER_EVENT_RX3_TMDS_EMP_DETECT,
#if(_HDMI_FRL_MAC_RX3_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_RX3_HDMI_FRL_PACKET_DETECT,

#if(_HDMI_ADVANCED_HDR10_SUPPORT_MODE != _ADVANCED_HDR10_NONE)
    _SCALER_TIMER_EVENT_RX3_HDMI_FRL_ADVANCED_HDR10_DETECT,
#endif

#if(_DM_FUNCTION == _ON)
    _SCALER_TIMER_EVENT_RX3_HDMI_FRL_DM_DETECT,
#endif

    _SCALER_TIMER_EVENT_RX3_HDMI_FRL_EMP_DETECT,

#if(_HDMI_FRL_REBUILD_PHY_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_RX3_HDMI_FRL_SIGNAL_DETECT,
#endif
#endif
#endif

#if(_TMDS_HPD_WAITING_TIMER_EVENT_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_RX3_TMDS_HPD_LOW_FINISH,
    _SCALER_TIMER_EVENT_RX3_TMDS_Z0_LOW_FINISH,
    _SCALER_TIMER_EVENT_RX3_TMDS_HPD_Z0_INTERVAL_FINISH,
#endif

#if(_TMDS_HPD_TIMER_EVENT_ACTIVE_TYPE_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_ACTIVE_TYPE_RX3_TMDS_HPD_LOW_FINISH,
    _SCALER_TIMER_EVENT_ACTIVE_TYPE_RX3_TMDS_HPD_Z0_INTERVAL_FINISH,
    _SCALER_TIMER_EVENT_ACTIVE_TYPE_RX3_TMDS_Z0_LOW_FINISH,
#endif
#endif
#if(_TMDS_MAC_RX4_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_RX4_TMDS_VIDEO_DETECT,
#if(_HDMI_MAC_RX4_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_RX4_TMDS_HDMI_PACKET_DETECT,

#if(_HDMI_ADVANCED_HDR10_SUPPORT_MODE != _ADVANCED_HDR10_NONE)
    _SCALER_TIMER_EVENT_RX4_HDMI_ADVANCED_HDR10_DETECT,
#endif
#if(_DM_FUNCTION == _ON)
    _SCALER_TIMER_EVENT_RX4_HDMI_DM_DETECT,
#endif
    _SCALER_TIMER_EVENT_RX4_TMDS_EMP_DETECT,
#if(_HDMI_FRL_MAC_RX4_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_RX4_HDMI_FRL_PACKET_DETECT,

#if(_HDMI_ADVANCED_HDR10_SUPPORT_MODE != _ADVANCED_HDR10_NONE)
    _SCALER_TIMER_EVENT_RX4_HDMI_FRL_ADVANCED_HDR10_DETECT,
#endif

#if(_DM_FUNCTION == _ON)
    _SCALER_TIMER_EVENT_RX4_HDMI_FRL_DM_DETECT,
#endif

    _SCALER_TIMER_EVENT_RX4_HDMI_FRL_EMP_DETECT,

#if(_HDMI_FRL_REBUILD_PHY_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_RX4_HDMI_FRL_SIGNAL_DETECT,
#endif
#endif
#endif

#if(_TMDS_HPD_WAITING_TIMER_EVENT_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_RX4_TMDS_HPD_LOW_FINISH,
    _SCALER_TIMER_EVENT_RX4_TMDS_Z0_LOW_FINISH,
    _SCALER_TIMER_EVENT_RX4_TMDS_HPD_Z0_INTERVAL_FINISH,
#endif

#if(_TMDS_HPD_TIMER_EVENT_ACTIVE_TYPE_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_ACTIVE_TYPE_RX4_TMDS_HPD_LOW_FINISH,
    _SCALER_TIMER_EVENT_ACTIVE_TYPE_RX4_TMDS_HPD_Z0_INTERVAL_FINISH,
    _SCALER_TIMER_EVENT_ACTIVE_TYPE_RX4_TMDS_Z0_LOW_FINISH,
#endif
#endif

#if(_TMDS_Z0_POWER_SAVING_TOGGLE_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_TMDS_Z0_POWER_SAVING_TOGGLE_LOW_DUTY,
    _SCALER_TIMER_EVENT_TMDS_Z0_POWER_SAVING_TOGGLE_HIGH_DUTY,
#endif

#if(_HDMI20_SUPPORT == _ON)

#if(_HDMI20_MAC_RX3_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_RX3_HDMI2_FORMAT_RESET_WAIT,
    _SCALER_TIMER_EVENT_RX3_HDMI2_SCRAMBLE_DETECT_TIMEOUT,
#endif

#if(_HDMI20_MAC_RX4_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_RX4_HDMI2_FORMAT_RESET_WAIT,
    _SCALER_TIMER_EVENT_RX4_HDMI2_SCRAMBLE_DETECT_TIMEOUT,
#endif

#endif // #if(_HDMI20_SUPPORT == _ON)

#endif // #if(_HDMI_SUPPORT == _ON)

#if(_HDCP_2_2_SUPPORT == _ON)
#if(_TMDS_MAC_RX3_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_RX3_HDCP2_REAUTH,
#endif
#if(_TMDS_MAC_RX4_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_RX4_HDCP2_REAUTH,
#endif
#endif

#if((_AUDIO_SUPPORT == _ON) || (_DP_RX_MST2SST_AUDIO_SUPPORT == _ON))
#if(_DP_AUDIO_RX0_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_AUDIO_RX0_LOAD_STABLE_I_CODE,
#endif
#if(_DP_AUDIO_RX1_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_AUDIO_RX1_LOAD_STABLE_I_CODE,
#endif
#if(_DP_AUDIO_RX2_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_AUDIO_RX2_LOAD_STABLE_I_CODE,
#endif
#if(_DP_AUDIO_RX3_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_AUDIO_RX3_LOAD_STABLE_I_CODE,
#endif
#if(_DP_AUDIO_RX4_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_AUDIO_RX4_LOAD_STABLE_I_CODE,
#endif

#endif // End of #if((_AUDIO_SUPPORT == _ON) || (_DP_RX_MST2SST_AUDIO_SUPPORT == _ON))

#if(_AUDIO_SUPPORT == _ON)
#if(_HDMI_AUDIO_RX3_SUPPORT == _ON)
#if(_HDMI_AUDIO_SPREAD_PCODE_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_HDMI_AUDIO_RX3_ENABLE_SPREAD_P_CODE,
#endif
    _SCALER_TIMER_EVENT_HDMI_AUDIO_RX3_LOAD_STABLE_I_CODE,
#if(_HDMI_AUDIO_FW_TRACKING_MODE_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_HDMI_AUDIO_RX3_FW_TRACKING_PREPARING,
    _SCALER_TIMER_EVENT_HDMI_AUDIO_RX3_FW_TRACKING_TIMEOUT,
#endif
#endif // End of #if(_HDMI_AUDIO_RX3_SUPPORT == _ON)

#if(_HDMI_AUDIO_RX4_SUPPORT == _ON)
#if(_HDMI_AUDIO_SPREAD_PCODE_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_HDMI_AUDIO_RX4_ENABLE_SPREAD_P_CODE,
#endif
    _SCALER_TIMER_EVENT_HDMI_AUDIO_RX4_LOAD_STABLE_I_CODE,
#if(_HDMI_AUDIO_FW_TRACKING_MODE_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_HDMI_AUDIO_RX4_FW_TRACKING_PREPARING,
    _SCALER_TIMER_EVENT_HDMI_AUDIO_RX4_FW_TRACKING_TIMEOUT,
#endif
#endif // End of #if(_HDMI_AUDIO_RX4_SUPPORT == _ON)

#if(_AUDIO_ARC_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_ARC_TX_DRIVING_CHANGE_KEEPOUT_TIMEOUT,
#if(_AUDIO_EARC_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_ARC_TX_FORCE_EARC_DISC_INIT_BY_HPD_TOGGLE_TIMEOUT,
#endif // End of #if(_AUDIO_EARC_SUPPORT == _ON)
#endif // End of #if(_AUDIO_ARC_SUPPORT == _ON)
#endif // End of #if(_AUDIO_SUPPORT == _ON)

#if(_DP_SUPPORT == _ON)
#if(_D0_DP_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX0_VALID_SIGNAL_DETECT_CHECK,
    _SCALER_TIMER_EVENT_DP_RX0_HOTPLUG_ASSERTED,
    _SCALER_TIMER_EVENT_DP_RX0_HDCP_LONG_HOTPLUG_EVENT,
    _SCALER_TIMER_EVENT_DP_RX0_LINK_STATUS_IRQ,

#if(_DP_HDCP_2_2_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX0_HDCP2_CPIRQ_EVENT,
    _SCALER_TIMER_EVENT_DP_RX0_HDCP2_REPEATER_PROC_TIMEOUT,
    _SCALER_TIMER_EVENT_DP_RX0_HDCP2_LONG_HOTPLUG_EVENT,
#endif

    _SCALER_TIMER_EVENT_DP_RX0_AUX_CH_NO_POWER_CHECK_DEBOUNCE,
#if(_DP_MST_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX0_SOURCE_WRITE_POWER_UP_TIMEOUT,
    _SCALER_TIMER_EVENT_DP_RX0_MSG_TIMEOUT_EVENT,
    _SCALER_TIMER_EVENT_DP_RX0_UP_REQUEST_PROCESSING,
#endif // End of #if(_DP_MST_SUPPORT == _ON)
#endif // End of #if(_D0_DP_SUPPORT == _ON)

#if(_D1_DP_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX1_VALID_SIGNAL_DETECT_CHECK,
    _SCALER_TIMER_EVENT_DP_RX1_HOTPLUG_ASSERTED,
    _SCALER_TIMER_EVENT_DP_RX1_HDCP_LONG_HOTPLUG_EVENT,
    _SCALER_TIMER_EVENT_DP_RX1_LINK_STATUS_IRQ,

#if(_DP_HDCP_2_2_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX1_HDCP2_CPIRQ_EVENT,
    _SCALER_TIMER_EVENT_DP_RX1_HDCP2_REPEATER_PROC_TIMEOUT,
    _SCALER_TIMER_EVENT_DP_RX1_HDCP2_LONG_HOTPLUG_EVENT,
#endif

    _SCALER_TIMER_EVENT_DP_RX1_AUX_CH_NO_POWER_CHECK_DEBOUNCE,
#if(_DP_MST_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX1_SOURCE_WRITE_POWER_UP_TIMEOUT,
    _SCALER_TIMER_EVENT_DP_RX1_MSG_TIMEOUT_EVENT,
    _SCALER_TIMER_EVENT_DP_RX1_UP_REQUEST_PROCESSING,
#endif // End of #if(_DP_MST_SUPPORT == _ON)
#endif // End of #if(_D1_DP_SUPPORT == _ON)

#if(_D2_DP_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX2_VALID_SIGNAL_DETECT_CHECK,
    _SCALER_TIMER_EVENT_DP_RX2_HOTPLUG_ASSERTED,
    _SCALER_TIMER_EVENT_DP_RX2_HDCP_LONG_HOTPLUG_EVENT,
    _SCALER_TIMER_EVENT_DP_RX2_LINK_STATUS_IRQ,

#if(_DP_HDCP_2_2_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX2_HDCP2_CPIRQ_EVENT,
    _SCALER_TIMER_EVENT_DP_RX2_HDCP2_REPEATER_PROC_TIMEOUT,
    _SCALER_TIMER_EVENT_DP_RX2_HDCP2_LONG_HOTPLUG_EVENT,
#endif

    _SCALER_TIMER_EVENT_DP_RX2_AUX_CH_NO_POWER_CHECK_DEBOUNCE,
#if(_DP_MST_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX2_SOURCE_WRITE_POWER_UP_TIMEOUT,
    _SCALER_TIMER_EVENT_DP_RX2_MSG_TIMEOUT_EVENT,
    _SCALER_TIMER_EVENT_DP_RX2_UP_REQUEST_PROCESSING,
#endif // End of #if(_DP_MST_SUPPORT == _ON)
#endif // End of #if(_D2_DP_SUPPORT == _ON)

#if(_DP_MAC_RX0_SUPPORT == _ON)
#if((_DP_FREESYNC_SUPPORT == _ON) || (_DP_FREESYNC_II_SUPPORT == _ON))
    _SCALER_TIMER_EVENT_DP_RX0_SPD_INFOFRAME_DETECTING_DONE,
#endif
#if(_DP_ADAPTIVESYNC_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX0_ADAPTIVESYNC_SDP_DETECTING_DONE,
#endif
#if(_DP_HDR10_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX0_HDR_INFOFRAME_DETECTING_DONE,
#endif
#if(_DP_MAC_RX0_ADVANCED_HDR10_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX0_ADVANCED_HDR10_DETECTING_DONE,
#endif
#if(_DP_MAC_RX0_DM_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX0_DM_VSIF_DETECTING_DONE,
#endif
#if(_AUDIO_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX0_AUDIO_INFOFRAME_DETECTING_DONE,
#endif
#if(_DP_TX_DSC_PASSTHROUGH_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX0_PPS_SDP_INFOFRAME_DETECTING_DONE,
#endif
#if(_DP_MAC_RX0_DSC_DECODER_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_MAC_STREAM_RX0_PPS_RECEIVE_TIMEOUT,
#endif
#endif // End of #if(_DP_MAC_RX0_SUPPORT == _ON)

#if(_DP_MAC_RX1_SUPPORT == _ON)
#if((_DP_FREESYNC_SUPPORT == _ON) || (_DP_FREESYNC_II_SUPPORT == _ON))
    _SCALER_TIMER_EVENT_DP_RX1_SPD_INFOFRAME_DETECTING_DONE,
#endif
#if(_DP_ADAPTIVESYNC_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX1_ADAPTIVESYNC_SDP_DETECTING_DONE,
#endif
#if(_DP_HDR10_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX1_HDR_INFOFRAME_DETECTING_DONE,
#endif
#if(_DP_MAC_RX1_ADVANCED_HDR10_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX1_ADVANCED_HDR10_DETECTING_DONE,
#endif
#if(_DP_MAC_RX1_DM_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX1_DM_VSIF_DETECTING_DONE,
#endif
#if(_AUDIO_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX1_AUDIO_INFOFRAME_DETECTING_DONE,
#endif
#if(_DP_TX_DSC_PASSTHROUGH_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX1_PPS_SDP_INFOFRAME_DETECTING_DONE,
#endif
#if(_DP_MAC_RX1_DSC_DECODER_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_MAC_STREAM_RX1_PPS_RECEIVE_TIMEOUT,
#endif
#endif // End of #if(_DP_MAC_RX1_SUPPORT == _ON)

#if(_DP_MAC_RX2_SUPPORT == _ON)
#if((_DP_FREESYNC_SUPPORT == _ON) || (_DP_FREESYNC_II_SUPPORT == _ON))
    _SCALER_TIMER_EVENT_DP_RX2_SPD_INFOFRAME_DETECTING_DONE,
#endif
#if(_DP_ADAPTIVESYNC_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX2_ADAPTIVESYNC_SDP_DETECTING_DONE,
#endif
#if(_DP_HDR10_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX2_HDR_INFOFRAME_DETECTING_DONE,
#endif
#if(_DP_MAC_RX2_ADVANCED_HDR10_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX2_ADVANCED_HDR10_DETECTING_DONE,
#endif
#if(_DP_MAC_RX2_DM_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX2_DM_VSIF_DETECTING_DONE,
#endif
#if(_AUDIO_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX2_AUDIO_INFOFRAME_DETECTING_DONE,
#endif
#if(_DP_TX_DSC_PASSTHROUGH_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX2_PPS_SDP_INFOFRAME_DETECTING_DONE,
#endif
#if(_DP_MAC_RX2_DSC_DECODER_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_MAC_STREAM_RX2_PPS_RECEIVE_TIMEOUT,
#endif
#endif // End of #if(_DP_MAC_RX2_SUPPORT == _ON)

#if(_DP_MAC_RX3_SUPPORT == _ON)
#if((_DP_FREESYNC_SUPPORT == _ON) || (_DP_FREESYNC_II_SUPPORT == _ON))
    _SCALER_TIMER_EVENT_DP_RX3_SPD_INFOFRAME_DETECTING_DONE,
#endif
#if(_DP_ADAPTIVESYNC_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX3_ADAPTIVESYNC_SDP_DETECTING_DONE,
#endif
#if(_DP_HDR10_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX3_HDR_INFOFRAME_DETECTING_DONE,
#endif
#if(_DP_MAC_RX3_ADVANCED_HDR10_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX3_ADVANCED_HDR10_DETECTING_DONE,
#endif
#if(_DP_MAC_RX3_DM_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX3_DM_VSIF_DETECTING_DONE,
#endif
#if(_AUDIO_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX3_AUDIO_INFOFRAME_DETECTING_DONE,
#endif
#if(_DP_TX_DSC_PASSTHROUGH_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX3_PPS_SDP_INFOFRAME_DETECTING_DONE,
#endif
#if(_DP_MAC_RX3_DSC_DECODER_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_MAC_STREAM_RX3_PPS_RECEIVE_TIMEOUT,
#endif
#endif // End of #if(_DP_MAC_RX3_SUPPORT == _ON)

#if(_DP_MAC_RX4_SUPPORT == _ON)
#if((_DP_FREESYNC_SUPPORT == _ON) || (_DP_FREESYNC_II_SUPPORT == _ON))
    _SCALER_TIMER_EVENT_DP_RX4_SPD_INFOFRAME_DETECTING_DONE,
#endif
#if(_DP_ADAPTIVESYNC_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX4_ADAPTIVESYNC_SDP_DETECTING_DONE,
#endif
#if(_DP_HDR10_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX4_HDR_INFOFRAME_DETECTING_DONE,
#endif
#if(_DP_MAC_RX4_ADVANCED_HDR10_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX4_ADVANCED_HDR10_DETECTING_DONE,
#endif
#if(_DP_MAC_RX4_DM_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX4_DM_VSIF_DETECTING_DONE,
#endif
#if(_AUDIO_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX4_AUDIO_INFOFRAME_DETECTING_DONE,
#endif
#if(_DP_TX_DSC_PASSTHROUGH_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX4_PPS_SDP_INFOFRAME_DETECTING_DONE,
#endif
#if(_DP_MAC_RX4_DSC_DECODER_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_MAC_STREAM_RX4_PPS_RECEIVE_TIMEOUT,
#endif
#endif // End of #if(_DP_MAC_RX4_SUPPORT == _ON))

#if(_DP_TX_SUPPORT == _ON)
#if(_DP_MST_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_TX_FORCE_REBUILD_TOPOLOGY_EVENT,
    _SCALER_TIMER_EVENT_DP_RX_MSG_COUNT_RESET_EVENT,
    _SCALER_TIMER_EVENT_DP_TX_MSG_COUNT_RESET_EVENT,

#if(_DP_MST_TX_PLUG_CSN_DEBOUNCE_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_TX_PLUG_CSN_DEBOUNCING,
#endif
#if(_DP_TX_128B132B_CODING_TYPE_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_TX_ENUM_MSG_REPLY_PBN_WAIT_TIMEOUT,
#endif
#endif

#if(_DP_TX_FEC_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_TX_FEC_DECODE_DIS_FAIL_RETRAIN,
#endif

#if(_DP_TX_128B132B_CODING_TYPE_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_TX_LT_TIMEOUT,
    _SCALER_TIMER_EVENT_DP_TX_AUX_RD_INTERVAL,
#endif

    _SCALER_TIMER_EVENT_DP_TX_HPD_DEBOUNCE,
    _SCALER_TIMER_EVENT_DP_TX_DFP_WAKEUP,
    _SCALER_TIMER_EVENT_DP_TX_HDCP_WAITING_TO_READ_R0,
    _SCALER_TIMER_EVENT_DP_TX_HDCP_WAITING_FOR_V_READY,
    _SCALER_TIMER_EVENT_DP_TX_HDCP_POLLING_V_READY,

#if(_DP_HDCP_2_2_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_TX_HDCP2_WAITING_TO_READ_CERTIFICATE,
    _SCALER_TIMER_EVENT_DP_TX_HDCP2_WAITING_TO_READ_H_PRIME,
    _SCALER_TIMER_EVENT_DP_TX_HDCP2_WAITING_TO_READ_PAIRING_INFO,
    _SCALER_TIMER_EVENT_DP_TX_HDCP2_WAITING_TO_ENCRYPT_DATA,
    _SCALER_TIMER_EVENT_DP_TX_HDCP2_WAITING_FOR_V_READY,
    _SCALER_TIMER_EVENT_DP_TX_HDCP2_POLLING_V_READY,
    _SCALER_TIMER_EVENT_DP_TX_HDCP2_WAITING_TO_READ_M_PRIME,
#endif

#if(_DP_HDCP14_RX0_REPEATER_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX0_HDCP_CPIRQ_EVENT,
    _SCALER_TIMER_EVENT_DP_RX0_HDCP_REPEATER_PROC_TIMEOUT,
    _SCALER_TIMER_EVENT_DP_RX0_HDCP_READ_IRQ_TIMEOUT,
#endif

#if(_DP_HDCP14_RX1_REPEATER_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX1_HDCP_CPIRQ_EVENT,
    _SCALER_TIMER_EVENT_DP_RX1_HDCP_REPEATER_PROC_TIMEOUT,
    _SCALER_TIMER_EVENT_DP_RX1_HDCP_READ_IRQ_TIMEOUT,
#endif

#if(_DP_HDCP14_RX2_REPEATER_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX2_HDCP_CPIRQ_EVENT,
    _SCALER_TIMER_EVENT_DP_RX2_HDCP_REPEATER_PROC_TIMEOUT,
    _SCALER_TIMER_EVENT_DP_RX2_HDCP_READ_IRQ_TIMEOUT,
#endif
#endif // End of #if(_DP_TX_SUPPORT == _ON)
#endif // End of #if(_DP_SUPPORT == _ON)

#if((_TYPE_C_PORT_CTRL_SUPPORT == _ON) && (_PORT_CTRL_EMBEDDED_SUPPORT == _ON))
#if(_EMB_TYPE_C_0_MAPPING != _VALUE_NO_TYPE_C_PORT)
    _SCALER_TIMER_EVENT_CC_0_STATE_TO_UNATTACH,
    _SCALER_TIMER_EVENT_PD_0_PPS_TIMEOUT,
    _SCALER_TIMER_EVENT_PD_0_SRC_EPR_KEEP_ALIVE_TIMEOUT,
    _SCALER_TIMER_EVENT_PD_0_SEND_HARD_RST,
    _SCALER_TIMER_EVENT_PD_0_SNK_HARD_RST_TIMEOUT,
    _SCALER_TIMER_EVENT_PD_0_S8_HRST,
    _SCALER_TIMER_EVENT_PD_0_CLR_REQ_WAIT,
    _SCALER_TIMER_EVENT_PD_0_CLR_PARTNER_ALT_SUPPORT,
    _SCALER_TIMER_EVENT_PD_0_TPC_ERROR_RECOVERY,
    _SCALER_TIMER_EVENT_PD_0_T480_ERROR_RECOVERY,
    _SCALER_TIMER_EVENT_PD_0_SRC_TURN_OFF_POWER,
    _SCALER_TIMER_EVENT_PD_0_SRC_TURN_ON_POWER,
    _SCALER_TIMER_EVENT_PD_0_CLR_PRS_WAIT,
    _SCALER_TIMER_EVENT_PD_0_CLR_DRS_WAIT,
    _SCALER_TIMER_EVENT_PD_0_CLR_VCS_WAIT,
    _SCALER_TIMER_EVENT_PD_0_DFP_START_ALT_MODE,
    _SCALER_TIMER_EVENT_PD_0_LENOVO_RESP_TIMEOUT,
    _SCALER_TIMER_EVENT_PD_0_VDM_RESP_CONFLICT_TIMEOUT,
    _SCALER_TIMER_EVENT_PD_0_CLR_ATTENTION_WAIT,
    _SCALER_TIMER_EVENT_PD_0_CLR_GET_SNK_CAP_WAIT,
    _SCALER_TIMER_EVENT_PD_0_CLR_VDMMSG_WAIT,
    _SCALER_TIMER_EVENT_PD_0_CLR_VDM_BUSY_FLAG,

#if(_EMB_TYPE_C_0_PMIC_TYPE != _PMIC_NONE)
    _SCALER_TIMER_EVENT_TYPE_C_0_PMIC_TRACKING,
    _SCALER_TIMER_EVENT_TYPE_C_0_PMIC_SAFETY_PROTECT,
    _SCALER_TIMER_EVENT_TYPE_C_0_PMIC_POLLING_OCP,
#endif // End of #if(_EMB_TYPE_C_0_PMIC_TYPE != _PMIC_NONE)
#endif // End of #if(_EMB_TYPE_C_0_MAPPING != _VALUE_NO_TYPE_C_PORT)

#if(_EMB_TYPE_C_1_MAPPING != _VALUE_NO_TYPE_C_PORT)
    _SCALER_TIMER_EVENT_CC_1_STATE_TO_UNATTACH,
    _SCALER_TIMER_EVENT_PD_1_PPS_TIMEOUT,
    _SCALER_TIMER_EVENT_PD_1_SRC_EPR_KEEP_ALIVE_TIMEOUT,
    _SCALER_TIMER_EVENT_PD_1_SEND_HARD_RST,
    _SCALER_TIMER_EVENT_PD_1_SNK_HARD_RST_TIMEOUT,
    _SCALER_TIMER_EVENT_PD_1_S8_HRST,
    _SCALER_TIMER_EVENT_PD_1_CLR_REQ_WAIT,
    _SCALER_TIMER_EVENT_PD_1_CLR_PARTNER_ALT_SUPPORT,
    _SCALER_TIMER_EVENT_PD_1_TPC_ERROR_RECOVERY,
    _SCALER_TIMER_EVENT_PD_1_T480_ERROR_RECOVERY,
    _SCALER_TIMER_EVENT_PD_1_SRC_TURN_OFF_POWER,
    _SCALER_TIMER_EVENT_PD_1_SRC_TURN_ON_POWER,
    _SCALER_TIMER_EVENT_PD_1_CLR_PRS_WAIT,
    _SCALER_TIMER_EVENT_PD_1_CLR_DRS_WAIT,
    _SCALER_TIMER_EVENT_PD_1_CLR_VCS_WAIT,
    _SCALER_TIMER_EVENT_PD_1_DFP_START_ALT_MODE,
    _SCALER_TIMER_EVENT_PD_1_LENOVO_RESP_TIMEOUT,
    _SCALER_TIMER_EVENT_PD_1_VDM_RESP_CONFLICT_TIMEOUT,
    _SCALER_TIMER_EVENT_PD_1_CLR_ATTENTION_WAIT,
    _SCALER_TIMER_EVENT_PD_1_CLR_GET_SNK_CAP_WAIT,
    _SCALER_TIMER_EVENT_PD_1_CLR_VDMMSG_WAIT,
    _SCALER_TIMER_EVENT_PD_1_CLR_VDM_BUSY_FLAG,

#if(_EMB_TYPE_C_1_PMIC_TYPE != _PMIC_NONE)
    _SCALER_TIMER_EVENT_TYPE_C_1_PMIC_TRACKING,
    _SCALER_TIMER_EVENT_TYPE_C_1_PMIC_SAFETY_PROTECT,
    _SCALER_TIMER_EVENT_TYPE_C_1_PMIC_POLLING_OCP,
#endif // End of #if(_EMB_TYPE_C_1_PMIC_TYPE != _PMIC_NONE)
#endif // End of #if(_EMB_TYPE_C_1_MAPPING != _VALUE_NO_TYPE_C_PORT)
#endif // End of #if((_TYPE_C_PORT_CTRL_SUPPORT == _ON) && (_PORT_CTRL_EMBEDDED_SUPPORT == _ON))

#if((_TYPE_C_PORT_CTRL_SUPPORT == _ON) && (_PORT_CTRL_TCPM_SUPPORT == _ON))
#if(_HW_TCPM_SUPPORT == _ON)
#if(_HW_TCPM_0_0_MAPPING != _VALUE_NO_TYPE_C_PORT)
    _SCALER_TIMER_EVENT_TCPM_0_0_SNK_HARD_RST_TIMEOUT,
    _SCALER_TIMER_EVENT_TCPM_0_0_CLR_REQ_WAIT,
    _SCALER_TIMER_EVENT_TCPM_0_0_CLR_PARTNER_ALT_SUPPORT,
    _SCALER_TIMER_EVENT_TCPM_0_0_T480_ERROR_RECOVERY,
    _SCALER_TIMER_EVENT_TCPM_0_0_SRC_TURN_OFF_POWER,
    _SCALER_TIMER_EVENT_TCPM_0_0_SRC_TURN_ON_POWER,
    _SCALER_TIMER_EVENT_TCPM_0_0_VDM_RESP_CONFLICT_TIMEOUT,
    _SCALER_TIMER_EVENT_TCPM_0_0_CLR_ATTENTION_WAIT,
    _SCALER_TIMER_EVENT_TCPM_0_0_CLR_GET_SNK_CAP_WAIT,
    _SCALER_TIMER_EVENT_TCPM_0_0_S8_HRST,
    _SCALER_TIMER_EVENT_TCPM_0_0_SEND_HARD_RST,
    _SCALER_TIMER_EVENT_TCPM_0_0_TPC_ERROR_RECOVERY,
    _SCALER_TIMER_EVENT_TCPM_0_0_CLR_PRS_WAIT,
    _SCALER_TIMER_EVENT_TCPM_0_0_CLR_DRS_WAIT,
    _SCALER_TIMER_EVENT_TCPM_0_0_CLR_VCS_WAIT,
    _SCALER_TIMER_EVENT_TCPM_0_0_CLR_VDMMSG_WAIT,
    _SCALER_TIMER_EVENT_TCPM_0_0_CLR_VDM_BUSY_FLAG,
    _SCALER_TIMER_EVENT_TCPM_0_0_DFP_START_ALT_MODE,

#if(_PORT_CTRL_EMB_PD3_PPS_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_TCPM_0_0_PPS_TIMEOUT,
#endif

#if(_PORT_CTRL_TCPM_OVP_UVP_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_TCPM_0_0_OVP_UVP_CHECK,
#endif

#if((_TYPE_C_PMIC_SUPPORT == _ON) && (_PORT_CTRL_TCPM_PMIC_CHECK_SUPPORT == _ON))
     _SCALER_TIMER_EVENT_TCPM_0_0_PMIC_TRACKING,
     _SCALER_TIMER_EVENT_TCPM_0_0_PMIC_POLLING_OCP,
#endif

#endif // End of #if(_HW_TCPM_0_0_MAPPING != _VALUE_NO_TYPE_C_PORT)

#if(_HW_TCPM_0_1_MAPPING != _VALUE_NO_TYPE_C_PORT)
    _SCALER_TIMER_EVENT_TCPM_0_1_SNK_HARD_RST_TIMEOUT,
    _SCALER_TIMER_EVENT_TCPM_0_1_CLR_REQ_WAIT,
    _SCALER_TIMER_EVENT_TCPM_0_1_CLR_PARTNER_ALT_SUPPORT,
    _SCALER_TIMER_EVENT_TCPM_0_1_T480_ERROR_RECOVERY,
    _SCALER_TIMER_EVENT_TCPM_0_1_SRC_TURN_OFF_POWER,
    _SCALER_TIMER_EVENT_TCPM_0_1_SRC_TURN_ON_POWER,
    _SCALER_TIMER_EVENT_TCPM_0_1_VDM_RESP_CONFLICT_TIMEOUT,
    _SCALER_TIMER_EVENT_TCPM_0_1_CLR_ATTENTION_WAIT,
    _SCALER_TIMER_EVENT_TCPM_0_1_CLR_GET_SNK_CAP_WAIT,
    _SCALER_TIMER_EVENT_TCPM_0_1_S8_HRST,
    _SCALER_TIMER_EVENT_TCPM_0_1_SEND_HARD_RST,
    _SCALER_TIMER_EVENT_TCPM_0_1_TPC_ERROR_RECOVERY,
    _SCALER_TIMER_EVENT_TCPM_0_1_CLR_PRS_WAIT,
    _SCALER_TIMER_EVENT_TCPM_0_1_CLR_DRS_WAIT,
    _SCALER_TIMER_EVENT_TCPM_0_1_CLR_VCS_WAIT,
    _SCALER_TIMER_EVENT_TCPM_0_1_CLR_VDMMSG_WAIT,
    _SCALER_TIMER_EVENT_TCPM_0_1_CLR_VDM_BUSY_FLAG,
    _SCALER_TIMER_EVENT_TCPM_0_1_DFP_START_ALT_MODE,

#if(_PORT_CTRL_EMB_PD3_PPS_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_TCPM_0_1_PPS_TIMEOUT,
#endif

#if(_PORT_CTRL_TCPM_OVP_UVP_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_TCPM_0_1_OVP_UVP_CHECK,
#endif

#if((_TYPE_C_PMIC_SUPPORT == _ON) && (_PORT_CTRL_TCPM_PMIC_CHECK_SUPPORT == _ON))
     _SCALER_TIMER_EVENT_TCPM_0_1_PMIC_TRACKING,
     _SCALER_TIMER_EVENT_TCPM_0_1_PMIC_POLLING_OCP,
#endif

#endif // End of #if(_HW_TCPM_0_1_MAPPING != _VALUE_NO_TYPE_C_PORT)

#if(_HW_TCPM_1_0_MAPPING != _VALUE_NO_TYPE_C_PORT)
    _SCALER_TIMER_EVENT_TCPM_1_0_SNK_HARD_RST_TIMEOUT,
    _SCALER_TIMER_EVENT_TCPM_1_0_CLR_REQ_WAIT,
    _SCALER_TIMER_EVENT_TCPM_1_0_CLR_PARTNER_ALT_SUPPORT,
    _SCALER_TIMER_EVENT_TCPM_1_0_T480_ERROR_RECOVERY,
    _SCALER_TIMER_EVENT_TCPM_1_0_SRC_TURN_OFF_POWER,
    _SCALER_TIMER_EVENT_TCPM_1_0_SRC_TURN_ON_POWER,
    _SCALER_TIMER_EVENT_TCPM_1_0_VDM_RESP_CONFLICT_TIMEOUT,
    _SCALER_TIMER_EVENT_TCPM_1_0_CLR_ATTENTION_WAIT,
    _SCALER_TIMER_EVENT_TCPM_1_0_CLR_GET_SNK_CAP_WAIT,
    _SCALER_TIMER_EVENT_TCPM_1_0_S8_HRST,
    _SCALER_TIMER_EVENT_TCPM_1_0_SEND_HARD_RST,
    _SCALER_TIMER_EVENT_TCPM_1_0_TPC_ERROR_RECOVERY,
    _SCALER_TIMER_EVENT_TCPM_1_0_CLR_PRS_WAIT,
    _SCALER_TIMER_EVENT_TCPM_1_0_CLR_DRS_WAIT,
    _SCALER_TIMER_EVENT_TCPM_1_0_CLR_VCS_WAIT,
    _SCALER_TIMER_EVENT_TCPM_1_0_CLR_VDMMSG_WAIT,
    _SCALER_TIMER_EVENT_TCPM_1_0_CLR_VDM_BUSY_FLAG,
    _SCALER_TIMER_EVENT_TCPM_1_0_DFP_START_ALT_MODE,

#if(_PORT_CTRL_EMB_PD3_PPS_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_TCPM_1_0_PPS_TIMEOUT,
#endif

#if(_PORT_CTRL_TCPM_OVP_UVP_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_TCPM_1_0_OVP_UVP_CHECK,
#endif

#if((_TYPE_C_PMIC_SUPPORT == _ON) && (_PORT_CTRL_TCPM_PMIC_CHECK_SUPPORT == _ON))
     _SCALER_TIMER_EVENT_TCPM_1_0_PMIC_TRACKING,
     _SCALER_TIMER_EVENT_TCPM_1_0_PMIC_POLLING_OCP,
#endif

#endif // End of #if(_HW_TCPM_1_0_MAPPING != _VALUE_NO_TYPE_C_PORT)

#if(_HW_TCPM_1_1_MAPPING != _VALUE_NO_TYPE_C_PORT)
    _SCALER_TIMER_EVENT_TCPM_1_1_SNK_HARD_RST_TIMEOUT,
    _SCALER_TIMER_EVENT_TCPM_1_1_CLR_REQ_WAIT,
    _SCALER_TIMER_EVENT_TCPM_1_1_CLR_PARTNER_ALT_SUPPORT,
    _SCALER_TIMER_EVENT_TCPM_1_1_T480_ERROR_RECOVERY,
    _SCALER_TIMER_EVENT_TCPM_1_1_SRC_TURN_OFF_POWER,
    _SCALER_TIMER_EVENT_TCPM_1_1_SRC_TURN_ON_POWER,
    _SCALER_TIMER_EVENT_TCPM_1_1_VDM_RESP_CONFLICT_TIMEOUT,
    _SCALER_TIMER_EVENT_TCPM_1_1_CLR_ATTENTION_WAIT,
    _SCALER_TIMER_EVENT_TCPM_1_1_CLR_GET_SNK_CAP_WAIT,
    _SCALER_TIMER_EVENT_TCPM_1_1_S8_HRST,
    _SCALER_TIMER_EVENT_TCPM_1_1_SEND_HARD_RST,
    _SCALER_TIMER_EVENT_TCPM_1_1_TPC_ERROR_RECOVERY,
    _SCALER_TIMER_EVENT_TCPM_1_1_CLR_PRS_WAIT,
    _SCALER_TIMER_EVENT_TCPM_1_1_CLR_DRS_WAIT,
    _SCALER_TIMER_EVENT_TCPM_1_1_CLR_VCS_WAIT,
    _SCALER_TIMER_EVENT_TCPM_1_1_CLR_VDMMSG_WAIT,
    _SCALER_TIMER_EVENT_TCPM_1_1_CLR_VDM_BUSY_FLAG,
    _SCALER_TIMER_EVENT_TCPM_1_1_DFP_START_ALT_MODE,

#if(_PORT_CTRL_EMB_PD3_PPS_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_TCPM_1_1_PPS_TIMEOUT,
#endif

#if(_PORT_CTRL_TCPM_OVP_UVP_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_TCPM_1_1_OVP_UVP_CHECK,
#endif

#if((_TYPE_C_PMIC_SUPPORT == _ON) && (_PORT_CTRL_TCPM_PMIC_CHECK_SUPPORT == _ON))
     _SCALER_TIMER_EVENT_TCPM_1_1_PMIC_TRACKING,
     _SCALER_TIMER_EVENT_TCPM_1_1_PMIC_POLLING_OCP,
#endif

#endif // End of #if(_HW_TCPM_1_1_MAPPING != _VALUE_NO_TYPE_C_PORT)
#endif // End of #if(_HW_TCPM_SUPPORT == _ON)
#endif // End of #if((_TYPE_C_PORT_CTRL_SUPPORT == _ON) && (_PORT_CTRL_TCPM_SUPPORT == _ON))

#if(_ADVANCED_HDR10_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_ADVANCED_HDR10_ERROR_STATE_DETECT,
#endif

    _SCALER_TIMER_EVENT_PHASE_CALIBRATION,
    _SCALER_TIMER_EVENT_PHASE_CNT_CHECK,


// Background Fw Update Busy Timer
#if(_FW_UPDATE_BACKGROUND_SUPPORT == _ON)
#if(_DP_TX_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_BACKGROUND_FW_UPDATE_DPTX_BUSY,
#endif
#if(_DP_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_BACKGROUND_FW_UPDATE_DPRX_BUSY,
#endif
#if(_TYPE_C_PORT_CTRL_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_BACKGROUND_FW_UPDATE_TYPEC_BUSY,
#endif
#if(_DIGITAL_PORT_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_BACKGROUND_FW_UPDATE_MCCS_BUSY,
#endif
    _SCALER_TIMER_EVENT_BACKGROUND_FW_UPDATE_HDCP_BUSY,
#endif // End of #if(_FW_UPDATE_BACKGROUND_SUPPORT == _ON)

#ifndef __TIMER_EVENT_ID_SCALER__
} EnumTimerEventIdScaler;
#endif

#endif
