/********************************************************************************/
/*   Copyright (c) 2021 Realtek Semiconductor Corp. All rights reserved.        */
/*                                                                              */
/*   SPDX-License-Identifier: LicenseRef-Realtek-Proprietary                    */
/*                                                                              */
/*   This software component is confidential and proprietary to Realtek         */
/*   Semiconductor Corp. Disclosure, reproduction, redistribution, in whole     */
/*   or in part, of this work and its derivatives without express permission    */
/*   is prohibited.                                                             */
/********************************************************************************/

typedef enum
{
    _GOSD_IMAGE_SOURCE_RTK_LOGO_01 = 0,
    _GOSD_IMAGE_SOURCE_RTK_LOGO_02 = 1,
    _GOSD_IMAGE_SOURCE_RTK_LOGO_03 = 2,
    _GOSD_IMAGE_SOURCE_RTK_LOGO_04 = 3,
    _GOSD_IMAGE_SOURCE_RTK_LOGO_05 = 4,
    _GOSD_IMAGE_SOURCE_RTK_LOGO_06 = 5,
    _GOSD_IMAGE_SOURCE_RTK_LOGO_07 = 6,
    _GOSD_IMAGE_SOURCE_RTK_LOGO_08 = 7,
    _GOSD_IMAGE_SOURCE_RTK_LOGO_09 = 8,
    _GOSD_IMAGE_SOURCE_RTK_LOGO_10 = 9,
    _GOSD_IMAGE_SOURCE_RTK_LOGO_11 = 10,
    _GOSD_IMAGE_SOURCE_RTK_LOGO_12 = 11,
    _GOSD_IMAGE_SOURCE_RTK_LOGO_13 = 12,
    _GOSD_IMAGE_SOURCE_RTK_LOGO_14 = 13,
    _GOSD_IMAGE_SOURCE_RTK_LOGO_15 = 14,
    _GOSD_IMAGE_SOURCE_RTK_LOGO_16 = 15,
    _GOSD_IMAGE_SOURCE_RTK_LOGO_17 = 16,
    _GOSD_IMAGE_SOURCE_RTK_LOGO_18 = 17,
    _GOSD_IMAGE_SOURCE_RTK_LOGO_19 = 18,
    _GOSD_IMAGE_SOURCE_RTK_LOGO_20 = 19,
    _GOSD_IMAGE_SOURCE_RTK_LOGO_21 = 20,
    _GOSD_IMAGE_SOURCE_RTK_LOGO_22 = 21,
    _GOSD_IMAGE_SOURCE_RTK_LOGO_23 = 22,
    _GOSD_IMAGE_SOURCE_RTK_LOGO_24 = 23,
    _GOSD_IMAGE_SOURCE_RTK_LOGO_25 = 24,
    _GOSD_IMAGE_SOURCE_RTK_LOGO_26 = 25,
    _GOSD_IMAGE_SOURCE_RTK_LOGO_27 = 26,
    _GOSD_IMAGE_SOURCE_RTK_LOGO_28 = 27,
    _GOSD_IMAGE_SOURCE_RTK_LOGO_29 = 28,
    _GOSD_IMAGE_SOURCE_RTK_LOGO_30 = 29,
    _GOSD_IMAGE_SOURCE_RTK_LOGO_31 = 30,
    _GOSD_IMAGE_SOURCE_RTK_LOGO_32 = 31,
    _GOSD_IMAGE_SOURCE_MAINMENUBG = 32,
} EnumGosdImageSourceList;

#define _GOSD_IMAGE_SOURCE_NUMBER_USER               (33)

#if(_USER_EMBEDDED_GOSD_RESOURCE_FILE_SUPPORT == _ON)
#define _GOSD_IMAGE_SOURCE_FLASH_START_BANK          (HIWORD(UserCommonNVRamGetResourceAddress(_USER_RESOURCE_ID_GOSD_IMAGE_SOURCE)))
#else
#define _GOSD_IMAGE_SOURCE_FLASH_START_BANK          (25)
#endif

#if((_GOSD_IMAGE_SOURCE_NUMBER) != (_GOSD_IMAGE_SOURCE_NUMBER_USER))
#warning "_GOSD_IMAGE_SOURCE_NUMBER Should Be Same as _GOSD_IMAGE_SOURCE_NUMBER_USER!!!"
#endif

#define _GOSD_IMAGE_SOURCE_RTK_LOGO_01_WIDTH         (512)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_02_WIDTH         (512)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_03_WIDTH         (512)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_04_WIDTH         (512)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_05_WIDTH         (512)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_06_WIDTH         (512)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_07_WIDTH         (512)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_08_WIDTH         (512)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_09_WIDTH         (512)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_10_WIDTH         (512)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_11_WIDTH         (512)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_12_WIDTH         (512)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_13_WIDTH         (512)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_14_WIDTH         (512)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_15_WIDTH         (512)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_16_WIDTH         (512)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_17_WIDTH         (512)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_18_WIDTH         (512)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_19_WIDTH         (512)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_20_WIDTH         (512)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_21_WIDTH         (512)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_22_WIDTH         (512)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_23_WIDTH         (512)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_24_WIDTH         (512)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_25_WIDTH         (512)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_26_WIDTH         (512)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_27_WIDTH         (512)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_28_WIDTH         (512)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_29_WIDTH         (512)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_30_WIDTH         (512)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_31_WIDTH         (512)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_32_WIDTH         (512)
#define _GOSD_IMAGE_SOURCE_MAINMENUBG_WIDTH          (528)

#define _GOSD_IMAGE_SOURCE_RTK_LOGO_01_HEIGHT        (128)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_02_HEIGHT        (128)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_03_HEIGHT        (128)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_04_HEIGHT        (128)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_05_HEIGHT        (128)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_06_HEIGHT        (128)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_07_HEIGHT        (128)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_08_HEIGHT        (128)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_09_HEIGHT        (128)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_10_HEIGHT        (128)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_11_HEIGHT        (128)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_12_HEIGHT        (128)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_13_HEIGHT        (128)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_14_HEIGHT        (128)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_15_HEIGHT        (128)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_16_HEIGHT        (128)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_17_HEIGHT        (128)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_18_HEIGHT        (128)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_19_HEIGHT        (128)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_20_HEIGHT        (128)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_21_HEIGHT        (128)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_22_HEIGHT        (128)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_23_HEIGHT        (128)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_24_HEIGHT        (128)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_25_HEIGHT        (128)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_26_HEIGHT        (128)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_27_HEIGHT        (128)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_28_HEIGHT        (128)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_29_HEIGHT        (128)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_30_HEIGHT        (128)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_31_HEIGHT        (128)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_32_HEIGHT        (128)
#define _GOSD_IMAGE_SOURCE_MAINMENUBG_HEIGHT         (396)

#define _GOSD_IMAGE_SOURCE_RTK_LOGO_01_FORMAT        (_GOSD_PIXEL_FORMAT_INDEX8)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_02_FORMAT        (_GOSD_PIXEL_FORMAT_INDEX8)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_03_FORMAT        (_GOSD_PIXEL_FORMAT_INDEX8)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_04_FORMAT        (_GOSD_PIXEL_FORMAT_INDEX8)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_05_FORMAT        (_GOSD_PIXEL_FORMAT_INDEX8)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_06_FORMAT        (_GOSD_PIXEL_FORMAT_INDEX8)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_07_FORMAT        (_GOSD_PIXEL_FORMAT_INDEX8)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_08_FORMAT        (_GOSD_PIXEL_FORMAT_INDEX8)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_09_FORMAT        (_GOSD_PIXEL_FORMAT_INDEX8)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_10_FORMAT        (_GOSD_PIXEL_FORMAT_INDEX8)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_11_FORMAT        (_GOSD_PIXEL_FORMAT_INDEX8)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_12_FORMAT        (_GOSD_PIXEL_FORMAT_INDEX8)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_13_FORMAT        (_GOSD_PIXEL_FORMAT_INDEX8)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_14_FORMAT        (_GOSD_PIXEL_FORMAT_INDEX8)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_15_FORMAT        (_GOSD_PIXEL_FORMAT_INDEX8)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_16_FORMAT        (_GOSD_PIXEL_FORMAT_INDEX8)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_17_FORMAT        (_GOSD_PIXEL_FORMAT_INDEX8)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_18_FORMAT        (_GOSD_PIXEL_FORMAT_INDEX8)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_19_FORMAT        (_GOSD_PIXEL_FORMAT_INDEX8)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_20_FORMAT        (_GOSD_PIXEL_FORMAT_INDEX8)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_21_FORMAT        (_GOSD_PIXEL_FORMAT_INDEX8)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_22_FORMAT        (_GOSD_PIXEL_FORMAT_INDEX8)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_23_FORMAT        (_GOSD_PIXEL_FORMAT_INDEX8)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_24_FORMAT        (_GOSD_PIXEL_FORMAT_INDEX8)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_25_FORMAT        (_GOSD_PIXEL_FORMAT_INDEX8)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_26_FORMAT        (_GOSD_PIXEL_FORMAT_INDEX8)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_27_FORMAT        (_GOSD_PIXEL_FORMAT_INDEX8)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_28_FORMAT        (_GOSD_PIXEL_FORMAT_INDEX8)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_29_FORMAT        (_GOSD_PIXEL_FORMAT_INDEX8)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_30_FORMAT        (_GOSD_PIXEL_FORMAT_INDEX8)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_31_FORMAT        (_GOSD_PIXEL_FORMAT_INDEX8)
#define _GOSD_IMAGE_SOURCE_RTK_LOGO_32_FORMAT        (_GOSD_PIXEL_FORMAT_INDEX8)
#define _GOSD_IMAGE_SOURCE_MAINMENUBG_FORMAT         (_GOSD_PIXEL_FORMAT_ARGB8888)
